name: macOS Build

# macOS-only build to save GitHub Actions minutes
on:
  push:
    branches: [ macos-support ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-macos:
    name: macOS ${{ matrix.arch }}
    runs-on: macos-latest
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        include:
          - arch: Intel
            goos: darwin
            goarch: amd64
            output: TheBoysLauncher-amd64
          - arch: Apple Silicon
            goos: darwin
            goarch: arm64
            output: TheBoysLauncher-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build macOS ${{ matrix.arch }}
      timeout-minutes: 5  # Short timeout to save time
      run: |
        echo "Building macOS ${{ matrix.arch }}..."
        export GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=1
        go build -ldflags="-s -w -X main.version=v3.0.1-ci" -o ${{ matrix.output }} .

        # Verify the binary was created and show info
        if [[ -f "${{ matrix.output }}" ]]; then
          echo "✓ macOS ${{ matrix.arch }} build successful!"
          ls -la ${{ matrix.output }}
          file ${{ matrix.output }}
        else
          echo "❌ macOS ${{ matrix.arch }} build failed - no executable created"
          exit 1
        fi

    - name: Upload macOS ${{ matrix.arch }} binary
      uses: actions/upload-artifact@v4
      with:
        name: TheBoysLauncher-macOS-${{ matrix.arch }}
        path: ${{ matrix.output }}
        retention-days: 7  # Only keep for 7 days to save space