name: Dev CI + Auto-bump

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  packages: write

jobs:
  autobump:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    # Avoid running autobump when the push was made by the actions bot (prevents loop)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run auto-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./scripts/auto-bump.sh
          ./scripts/auto-bump.sh

  # dispatch-build removed: tag pushes now trigger build.yml directly
